name: pocketpub
description: A custom pub server built with Dart and PocketBase
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  http: ^1.4.0
  path: ^1.9.1
  crypto: ^3.0.6
  yaml: ^3.1.3
  archive: ^4.0.7
  pocketbase: ^0.22.0
  dotenv: ^4.2.0
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15